### ISSUE TITLE
add a license file

### ISSUE THREAD

**Issue by legrostdg** [hobarrera/sphinx-autorun#1]
Could you please add a LICENSE file to this project?

**Comment by hobarrera** [comment]
Added. It's a BSD 2-Clause.

**Comment by legrostdg** [comment]
Thanks! Could you make a new release with this change?

**Comment by hobarrera** [comment]
https://pypi.python.org/pypi/sphinx-autorun/1.0.2 :tada:

Official site is now at GitHub too, to help discoverability.

**Comment by legrostdg** [comment]
This does not seem to have the LICENSE file:

    $ tar xzvf v1.0.2.tar.gz 
    sphinx-autorun-1.0.2/
    sphinx-autorun-1.0.2/.gitignore
    sphinx-autorun-1.0.2/.travis.yml
    sphinx-autorun-1.0.2/MANIFEST.in
    sphinx-autorun-1.0.2/README.rst
    sphinx-autorun-1.0.2/doc/
    sphinx-autorun-1.0.2/doc/Makefile
    sphinx-autorun-1.0.2/doc/conf.py
    sphinx-autorun-1.0.2/doc/index.rst
    sphinx-autorun-1.0.2/setup.cfg
    sphinx-autorun-1.0.2/setup.py
    sphinx-autorun-1.0.2/sphinx_autorun/
    sphinx-autorun-1.0.2/sphinx_autorun/__init__.py
    sphinx-autorun-1.0.2/sphinx_autorun/pycon.py
    sphinx-autorun-1.0.2/tox.ini

**Comment by hobarrera** [comment]
Darn, yes, looks like I screwed up my branches and tags while testing all the GitLab->Travis migration.

Pushing v1.0.3 now.

**Comment by hobarrera** [comment]
v1.0.3 is properly packaged. 🎉 
Let me know if that worked okay.
