### ISSUE TITLE
building doc requires sphinxcontrib.autorun

### ISSUE THREAD

**Issue by legrostdg** [hobarrera/sphinx-autorun#3]
Building the doc seems to depend on sphinxcontrib.autorun, when it should depend on sphinx_autorun (as I understand it).

**Comment by legrostdg** [comment]
Also the doc seems outdated.

**Comment by hobarrera** [comment]
Where are you seeing `sphinxcontrib.autorun` being mentioned? I'm just seeing `sphinx_autorun`.

> And the doc seems outdated.

What exactly about the docs?

**Comment by legrostdg** [comment]
$ rgrep sphinxcontrib
    doc/conf.py:  'sphinxcontrib.autorun',
    doc/index.rst:To enable the autorun extension add 'sphinxcontrib.autorun' to the

So 'sphinxcontrib.autorun' is needed to build the docs, and the docs says that 'sphinxcontrib.autorun' should be added to enable the autorun extension...

**Comment by hobarrera** [comment]
Dah, sorry, sorry, I got my repos mixed up!

Yes, I'll address this ASAP.

**Comment by hobarrera** [comment]
Fixed in master and v1.0.4.

FWIW, `sphinxcontrib.autorun` is the original (abandoned) version on which this is inspired.

**Comment by hobarrera** [comment]
Thanks! Enjoy!
